name: CI
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Formatting
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
          echo "$STEPS_CONTEXT"
          yarn format
      - name: JS
        run: yarn lint:js
        continue-on-error: true
      - name: CSS
        run: yarn lint:css
      - name: Check on failures
        if: failure()
        run: exit 1

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Unit
        run: yarn test:unit