name: CI
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Formatting
        run: yarn format
      - name: JS
        run: yarn lint:js
      - name: CSS
        run: yarn lint:css


  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Unit
        run: yarn test:unit