name: CI
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: yarn
      - name: Formatting
        run: yarn format
      - name: CSS
        id: css
        run: yarn lint:css
        continue-on-error: true
      - name: JS
        id: js
        run: yarn lint:js
        continue-on-error: true
      - name: Check on failures
#        if: job.steps.css.status == 'failure' || job.steps.js.status == 'failure'
        run: |
          echo CSS - ${{ job.steps.css.status }}, JS - ${{ job.steps.js.status }}
          exit 1

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: yarn
      - name: Unit
        run: yarn test:unit

  deploy:
    needs: [linters, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: yarn
      - name: Building
        run: yarn build
      - name: Deploying
        run: npx netlify-cli deploy -s ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_ACCESS_TOKEN }}
