name: CI
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: yarn
      - name: Formatting
        run: yarn format
      - name: CSS
        run: yarn lint:css
      - name: JS
        run: yarn lint:js

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: yarn
      - name: Unit
        run: yarn test:unit

  deploy:
    needs: [linters, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: yarn
      - name: Building
        run: yarn build
      - name: Deploying
        run: npx netlify-cli deploy -s ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_ACCESS_TOKEN }}
