name: CI
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Formatting
        run: yarn format
      - name: CSS
        run: yarn lint:css
        continue-on-error: true
        id: css
      - name: JS
        run: yarn lint:js
        continue-on-error: true
        id: js
      - name: Check on failures
        if: job.steps.css.status == failure() # || job.steps.js.status == failure()
        run: exit 1

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Unit
        run: yarn test:unit
        continue-on-error: true
        id: unit
      - name: Check on failures
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        if: steps.unit.status == failure()
        run: ${{ toJson(steps) }} ${{ toJson(steps.unit) }} ${{ toJson(job) }} ${{ STEPS_CONTEXT }}