name: CI
on: [pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Formatting
        continue-on-error: true
        run: yarn format
      - name: CSS
        continue-on-error: true
        run: yarn lint:css
      - name: JS
        continue-on-error: true
        run: yarn lint:js

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Unit
        continue-on-error: true
        run: yarn test:unit